apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
    app: nginx
    lab: lab2
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
