apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replicaset
  labels:
    app: nginx
    lab: lab2
spec:
  # Количество реплик
  replicas: 3
  # Селектор для определения, какие поды принадлежат ReplicaSet
  selector:
    matchLabels:
      app: nginx
  # Шаблон пода
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
