---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  labels:
    app: postgres
    lab: lab2
spec:
  selector:
    app: postgres  # Должен совпадать с лейблами пода PostgreSQL
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP  # Доступен только внутри кластера
