---
apiVersion: v1
kind: Pod
metadata:
  name: go-app-pod
  labels:
    app: go-app
    lab: lab2
spec:
  containers:
    - name: go-app
      image: ghcr.io/some0person/containers-lab-1/app:latest
      ports:
        - containerPort: 8080
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
