apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    app: nginx
    lab: lab2
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30080 # фиксированный порт на ноде (опционально)
  type: NodePort # Доступен снаружи кластера через порт ноды